---
- name: clean out the package manager cache
  command: '{{ ansible_pkg_mgr }} clean all'

- name: install distribution-independent dependencies
  package:
    name: '{{ pkg_list | join(',') }}'
    state: latest
  vars:
    pkg_list:
     - ansible
     - augeas                   # developer UX
     - bc                       # for Bash math
     - bind                     #
     - bind-utils               #
     - bridge-utils             #
     - bsdtar                   # Origin build/package
     - btrfs-progs-devel        #
     - bzip2                    #
     - bzr                      #
     - createrepo               # Origin build/package
     - ctags                    #
     - deltarpm                 # vagrant-openshift, should remove
     - device-mapper-devel      #
     - e2fsprogs                #
     - ethtool                  #
     - firefox                  # Origin Web Console tests
     - fontconfig               #
     - gcc                      #
     - gcc-c++                  #
     - git                      # Interacting with repos
     - glibc-static             #
     - gnuplot                  # Origin test logger
     - gpgme                    # Image Signature verification dep (containers/image)
     - gpgme-devel              #
     - hg                       #
     - http-parser              # Origin Web Console tests
     - httpie                   # developer UX
     - iscsi-initiator-utils    #
     - java-1.?.0-openjdk-devel       #
     - jq                       # Origin e2e test, but should use jsonpath instead
     - kernel-devel             #
     - krb5-devel               # Origin build/package | Origin GSSAPI tests
     - libassuan                # Image Signature verification dep (containers/image)
     - libassuan-devel          #
     - libnetfilter_queue-devel #
     - libseccomp-devel         # Origin build/package (buildah)
     - libselinux-devel         #
     - libsemanage-python       # OpenShift-Ansible (upstream this)
     - lsof                     # developer UX
     - make                     # Interacting with repos
     - maven                  # for building java apps
     - mlocate                  # vagrant-openshift, should remove
     - npm                      # Origin Web Console tests
     - ntp                      #
     - openldap-clients         # Origin LDAP tests
     - openssl                  # Origin `test-cmd` tests
     - openvswitch              #
     - python-pip               # used for ansible plugin deps
     - python-dbus              # OpenShift-Ansible (upstream this)
     - rubygems                 #
     - screen                   # developer UX
     - socat                    # Origin `oc cluster up`
     - sqlite-devel             #
     - strace                   # developer UX
     - sysstat                  # developer UX
     - tcpdump                  # developer UX
     - tig                      # developer UX
     - tito                     # Origin build/package
     - tmux                     # developer UX
     - tree                     # developer UX
     - unzip                    # Origin build/package
     - vim                      # developer UX
     - wget                     # developer UX
     - xfsprogs                 #
     - xorg-x11-utils           # Origin Web Console tests
     - Xvfb                     # Origin Web Console tests
     - yum-utils                #
     - zip                      # Origin build/package

- name: install distribution-dependent dependencies
  package:
    name: '{{ item.package }}'
    state: latest
  when: ansible_distribution in item.distros
  with_items:
    - package: facter
      distros: [
        'CentOS',
        'RedHat'
      ]

- name: update all packages to latest state
  package:
    name: '*'
    state: latest

- name: install jUnit dependency for Ansible plugins
  pip:
    name: junit_xml
    state: present

- name: determine installed npm version
  command: "repoquery --pkgnarrow=installed --queryformat '%{version}' npm"
  register: origin_ci_installed_npm_version

- name: update npm to v3.7.3
  command: '/usr/bin/npm install npm@3.7.3 --global'
  when: origin_ci_installed_npm_version.stdout | version_compare('3.7.3', '<')

- name: upgrade to latest version
  command: '{{ ansible_pkg_mgr }} update'

- name: document all the installed packages for the build logs
  command: '{{ ansible_pkg_mgr }} list installed'
