---
- name: Register RHEL 7 Atomic OpenShift repositories
  yum_repository:
    name: 'rhel-7-server-ose-{{ item }}-rpms'
    state: present
    description: 'A repository of dependencies for Atomic OpenShift {{ item }}'
    baseurl: >
      https://mirror.openshift.com/enterprise/all/{{ item }}/latest/x86_64/os
    enabled: no
    gpgcheck: no
    gpgkey: >
      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release,
      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta,
      https://mirror.ops.rhcloud.com/libra/keys/RPM-GPG-KEY-redhat-openshifthosted
    failovermethod: priority
    sslverify: no
    username: "{{ lookup('env', ''MIRROR_OS_USER) }}"
    password: "{{ lookup('env', ''MIRROR_OS_PASS) }}"
  with_items:
    - '3.6'
    - '3.7'
    - '3.8'
    - '3.9'
    - '3.10'
    - '3.11'
    - '3.12'
  when: ansible_distribution == 'RedHat'

- name: turn on EPEL for the main dependency install
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Add RHEL 7 Server Ansible Repositories
  yum_repository:
    name: "rhel-7-server-ansible-{{ item }}-rpms"
    state: present
    description: "RHEL 7 Server Ansible {{ item }} Repository"
    baseurl: "https://mirror.openshift.com/enterprise/rhel/rhel-7-server-ansible-{{ item }}-rpms/"
    enabled: "{{ 'yes' if item == '2.4' else 'no' }}"
    gpgcheck: no
    gpgkey: >
      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release,
      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta,
      https://mirror.ops.rhcloud.com/libra/keys/RPM-GPG-KEY-redhat-openshifthosted
    sslverify: no
    username: "{{ lookup('env', ''MIRROR_OS_USER) }}"
    password: "{{ lookup('env', ''MIRROR_OS_PASS) }}"
  when: ansible_distribution == 'RedHat'
  with_items:
    - '2.4'
    - '2.6'
