---
- name: register RHEL 7 Atomic OpenShift repositories
  yum_repository:
    name: 'rhel-7-server-ose-{{ item }}-rpms'
    state: present
    description: 'A repository of dependencies for Atomic OpenShift {{ item }}'
    baseurl: >
      https://mirror.ops.rhcloud.com/enterprise/enterprise-{{ item }}/latest/RH7-RHAOS-{{ item }}/x86_64/os/,
      https://use-mirror1.ops.rhcloud.com/enterprise/enterprise-{{ item }}/latest/RH7-RHAOS-{{ item }}/x86_64/os/,
      https://use-mirror2.ops.rhcloud.com/enterprise/enterprise-{{ item }}/latest/RH7-RHAOS-{{ item }}/x86_64/os/,
      https://euw-mirror1.ops.rhcloud.com/enterprise/enterprise-{{ item }}/latest/RH7-RHAOS-{{ item }}/x86_64/os/
    gpgcheck: no
    gpgkey: >
      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release,
      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta,
      https://mirror.ops.rhcloud.com/libra/keys/RPM-GPG-KEY-redhat-openshifthosted
    failovermethod: priority
    sslverify: no
    sslclientcert: /var/lib/yum/client-cert.pem
    sslclientkey: /var/lib/yum/client-key.pem
  with_items:
    - 3.1
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - 3.7
  when: ansible_distribution == 'RedHat'

- name: add the signing key for the CentOS PaaS SIG repository
  rpm_key:
    key: https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_repos/files/origin/gpg_keys/openshift-ansible-CentOS-SIG-PaaS
    state: present
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: register the CentOS PaaS SIG repositories
  yum_repository:
    name: 'centos-paas-sig-openshift-origin{{ item.version }}-rpms'
    state: present
    description: 'CentOS PaaS SIG Origin {{ item.version | list | join(".") }} Repository'
    baseurl: 'https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin{{ item.version }}/'
    exclude: '{{ item.exclude | default(omit) }}'
    gpgcheck: no
    sslverify: no
    sslclientcert: /var/lib/yum/client-cert.pem
    sslclientkey: /var/lib/yum/client-key.pem
  with_items:
    - version: '13'
    - version: '14'
    - version: '15'
    - version: '36'
    - version: '37'
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: turn on EPEL for the main dependency install
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Add RHEL 7 Server Ansible 2.4 Repository
  yum_repository:
    name: 'rhel-7-server-ansible-2.4-rpms'
    state: present
    description: 'RHEL 7 Server Ansible Repository'
    baseurl: 'https://mirror.openshift.com/enterprise/rhel/rhel-7-server-ansible-2.4-rpms/'
    gpgcheck: no
    gpgkey: >
      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release,
      file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta,
      https://mirror.ops.rhcloud.com/libra/keys/RPM-GPG-KEY-redhat-openshifthosted
    sslverify: no
    sslclientcert: /var/lib/yum/client-cert.pem
    sslclientkey: /var/lib/yum/client-key.pem
  when: ansible_distribution == 'RedHat'
