---
- name: '{{ origin_ci_repository }} : initialize the source'
  file:
    path: '{{ origin_ci_gopath }}/src/github.com/openshift/{{ origin_ci_repository }}'
    state: 'directory'

- name: '{{ origin_ci_repository }} : initialize the source repository placeholder'
  command: 'git init'
  args:
    chdir: '{{ origin_ci_gopath }}/src/github.com/openshift/{{ origin_ci_repository }}'

- name: '{{ origin_ci_repository }} : allow pushes to happen to the current branch'
  command: '/usr/bin/git config receive.denyCurrentBranch ignore'
  args:
    chdir: '{{ origin_ci_gopath }}/src/github.com/openshift/{{ origin_ci_repository }}'

- name: '{{ origin_ci_repository }} : allow unsafe fast-forward pushes to the repository'
  command: '/usr/bin/git config receive.denyNonFastForwards false'
  args:
    chdir: '{{ origin_ci_gopath }}/src/github.com/openshift/{{ origin_ci_repository }}'

- name: '{{ origin_ci_repository }} : allow pushes to happen from the owning group'
  command: '/usr/bin/git config core.sharedRepository group'
  args:
    chdir: '{{ origin_ci_gopath }}/src/github.com/openshift/{{ origin_ci_repository }}'