---
- name: '{{ origin_ci_repository }} : clone the source repository'
  git:
    repo: 'https://github.com/openshift/{{ origin_ci_repository }}.git'
    clone: yes
    dest: '{{ origin_ci_gopath }}/src/github.com/openshift/{{ origin_ci_repository }}'
    accept_hostkey: yes

- name: '{{ origin_ci_repository }} : allow pushes to happen to the current branch'
  command: '/usr/bin/git config receive.denyCurrentBranch ignore'
  args:
    chdir: '{{ origin_ci_gopath }}/src/github.com/openshift/{{ origin_ci_repository }}'

- name: '{{ origin_ci_repository }} : allow unsafe fast-forward pushes to the repository'
  command: '/usr/bin/git config receive.denyNonFastForwards false'
  args:
    chdir: '{{ origin_ci_gopath }}/src/github.com/openshift/{{ origin_ci_repository }}'

- name: '{{ origin_ci_repository }} : allow pushes to happen from the owning group'
  command: '/usr/bin/git config core.sharedRepository group'
  args:
    chdir: '{{ origin_ci_gopath }}/src/github.com/openshift/{{ origin_ci_repository }}'