---
- name: ensure we have the parameters necessary to set up Docker storage
  hosts: 'localhost'
  connection: 'local'
  become: no
  gather_facts: no

  pre_tasks:
    - name: ensure all required variables are set
      fail:
        msg: 'This playbook requires {{ item }} to be set.'
      when: item not in vars and item not in hostvars[inventory_hostname]
      with_items:
        - origin_ci_hosts
        - origin_ci_connection
        - origin_ci_docker_volume_group

- name: ensure the host has been bootstrapped
  include: './../bootstrap/host.yml'

- name: partition the new space to be an LVM pool
  hosts: '{{ origin_ci_hosts }}'
  connection: '{{ origin_ci_connection }}'
  become: yes
  become_user: root
  gather_facts: yes

  tasks:
    - name: ensure we have the tools to work with logical volumes
      include: lvm2.yml

    - name: ensure the new space is empty
      command: '/sbin/wipefs -a /dev/xvdb'
      ignore_errors: true

    - name: ensure changes are synced to disk
      command: '/usr/bin/sync'

    - name: commit the new partition table
      command: '/usr/sbin/partprobe'

    - name: partition the new space
      script: './../files/partition.sh /dev/xvdb'

    - name: commit the new partition table
      command: '/usr/sbin/partprobe'

    - name: determine the partition with the largest index on the device # TODO: is there a better way to choose this?
      shell: '/usr/bin/ls -1 /dev/xvdb* | tail -n 1'
      register: origin_ci_device_partition

    - name: set up the volume group
      lvg:
        vg: '{{ origin_ci_docker_volume_group }}'
        pvs: '{{ origin_ci_device_partition.stdout }}'
        state: present
