---
- name:
  include_vars:
    file: python3.yml

- name: download lvm2 for non-RHEL8 hosts
  when: not supports_python3
  package:
    name: lvm2
    state: present

- name: download lvm2 for RHEL8 hosts
  when: supports_python3
  command: yum install -y lvm2
