---
- name: Create docker-storage-setup sysconfig
  file:
    path: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    state: touch

- name: Set VG for docker-storage-setup
  lineinfile:
    dest: /etc/sysconfig/docker-storage-setup
    line: "VG={{ origin_ci_docker_volume_group }}"

- name: Run docker-storage-setup
  command: docker-storage-setup
