---
- name: create a group for users that can talk to the Docker daemon
  group:
    name: docker

- name: add the user to the Docker daemon group
  user:
    name: '{{ origin_ci_user }}'
    group: docker

- name: enable insecure registry connections to local and test registries
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: "^INSECURE_REGISTRY=.*"
    line: "INSECURE_REGISTRY='--insecure-registry={{ origin_ci_insecure_registries | join(' --insecure-registry=') }}'"

- name: ensure no extra registries are added by the configuration
  lineinfile:
    backrefs: yes
    dest: /etc/sysconfig/docker
    regexp: '^ADD_REGISTRY=(.*)'
    line: '# ADD_REGISTRY=\1'

- name: log to json-file to avoid flooding journald
  lineinfile:
    backrefs: yes
    dest: /etc/sysconfig/docker
    regexp: '^OPTIONS=(.*) --log-driver=journald (.*)'
    line: 'OPTIONS=\1 --log-driver=json-file --log-opt max-size=50m \2'

- name: turn on docker daemon debugging
  lineinfile:
    backrefs: yes
    dest: /etc/sysconfig/docker
    regexp: "^OPTIONS='(.*)'"
    line: "OPTIONS='--debug \\1'"

- name: configure the OpenShift storage
  include: configure_openshift_storage.yml

- name: configure the Docker daemon storage
  include: configure_docker_daemon_storage.yml

- name: increase the default timeout for the Docker daemon service
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    regexp: '^TimeoutStartSec='
    line: 'TimeoutStartSec=10min'

- name: update systemd config and start the Docker service
  systemd:
    daemon_reload: yes
    name: docker
    enabled: yes
    state: started
